import {
    Plus,
    CloseEye,
    IconArticleMenu,
    OpenEye,
    AvatarDefault,
    IconCartMenu,
    IconManageMenu,
    IconStoreMenu,
    IconLogout,
    IconLightTheme,
    IconInputSearch,
    IconDarkTheme,
    IconArrowRight,
    IconFilter,
    IconLineSubMenu,
    IconSelectArrowButton,
    IconPlus,
    IconArrowButton,
} from './SVGIcon.tsx';

export default {
    Plus,
    CloseEye,
    IconFilter,
    IconLineSubMenu,
    IconInputSearch,
    OpenEye,
    AvatarDefault,
    IconManageMenu,
    IconSelectArrowButton,
    IconArrowButton,
    IconCartMenu,
    IconArticleMenu,
    IconLightTheme,
    IconPlus,
    IconArrowRight,
    IconDarkTheme,
    IconLogout,
    IconStoreMenu,
}