import {
    Plus,
    CloseEye,
    IconArticleMenu,
    OpenEye,
    AvatarDefault,
    IconCartMenu,
    IconManageMenu,
    IconStoreMenu,
    IconLogout,
    IconLightTheme,
    IconDarkTheme,
    IconArrowRight,
    IconLineSubMenu,
    IconArrowButton,
} from './SVGIcon.tsx';

export default {
    Plus,
    CloseEye,
    IconLineSubMenu,
    OpenEye,
    AvatarDefault,
    IconManageMenu,
    IconArrowButton,
    IconCartMenu,
    IconArticleMenu,
    IconLightTheme,
    IconArrowLeft: IconArrowRight,
    IconDarkTheme,
    IconLogout,
    IconStoreMenu,
}